language: node_js
notifications:
  email: false
node_js:
  - '10'
before_script:
  - npm prune
script:
  - npm run test:single
  - npm run check-coverage
after_success:
  - npm run report-coverage
  - npm run publish
